# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_destination_parent'),
        ('heroes', '0002_hero_destinations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='destinations',
        ),
        migrations.AddField(
            model_name='hero',
            name='destinations',
            field=models.ManyToManyField(blank=True, null=True, to='destinations.Destination'),
        ),
    ]
