# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_auto_20170223_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='destinations',
        ),
    ]
