# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 20:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tribes', '0001_initial'),
        ('destinations', '0003_destination_parent'),
        ('heroes', '0004_remove_hero_destinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_spent', models.CharField(max_length=100)),
                ('no_of_visits', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.Destination')),
                ('tribe', models.ManyToManyField(to='tribes.Tribe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
