# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0006_auto_20170223_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herodestination',
            name='days_spent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='herotip',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
