# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0007_auto_20170224_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.FileField(default='/media/posts/iceland.jpg', upload_to='icons')),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='herodestination',
            name='points',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
