# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 17:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Quick Help', max_length=100)),
                ('price', models.IntegerField(default=29)),
                ('description', models.CharField(default='I am here to help you with', max_length=300)),
                ('value_one', models.CharField(default='Save up to $300 on a trip', max_length=50)),
                ('value_two', models.CharField(default='Make the most out of the trip', max_length=50)),
                ('value_three', models.CharField(default='Connect with great locals', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('avatar', models.CharField(max_length=500)),
                ('video', models.CharField(max_length=500)),
                ('email', models.CharField(default='me@email.com', max_length=500)),
                ('about', models.CharField(max_length=1000)),
                ('is_expert', models.BooleanField(default=False)),
                ('subscribers', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gig',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile'),
        ),
    ]
