# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_expert',
            new_name='is_master',
        ),
    ]
