# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='cover_image',
            field=models.FileField(default='/media/posts/iceland.jpg', upload_to='posts'),
        ),
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.TextField(default='Get notified every time we publish a new tip, a new hack or a deal on Adventure Travel.', max_length=1000),
        ),
    ]
