# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        ('masters', '0001_initial'),
        ('tribes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bedge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Majorcan Eagle', max_length=60)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.FileField(default='/media/posts/iceland.jpg', upload_to='bedges')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField(default='Summary Here')),
                ('description', models.TextField(default='Description Here')),
                ('price_description', models.CharField(default='Between $60-$100', max_length=100)),
                ('completion_time', models.CharField(default='Up to 4 hours', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cover_image', models.FileField(default='/media/posts/iceland.jpg', upload_to='posts')),
                ('status', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Master')),
                ('bedge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quests.Bedge')),
                ('destination_reputation', models.ManyToManyField(related_name='destination_reputation', to='destinations.Destination')),
                ('destinations', models.ManyToManyField(to='destinations.Destination')),
                ('tribe_reputation', models.ManyToManyField(related_name='tribe_reputation', to='tribes.Tribe')),
                ('tribes', models.ManyToManyField(to='tribes.Tribe')),
            ],
        ),
    ]
