# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('cover_image', models.FileField(default='/media/posts/iceland.jpg', upload_to='posts')),
                ('description', models.TextField(default='Get notified every time we publish a new tip, a new hack or a deal on Adventure Travel.', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='quest',
            name='categories',
            field=models.ManyToManyField(to='quests.Categ'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='locations',
            field=models.ManyToManyField(to='quests.Location'),
        ),
    ]
