# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quests', '0002_auto_20170219_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='categ',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='category_subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='location_subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
