# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0004_auto_20170222_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='categories',
            new_name='tribes',
        ),
    ]
