# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField(default='Summary Here')),
                ('content', models.TextField(default='content')),
                ('gmaps_embed_url', models.TextField(blank=True)),
                ('country', models.CharField(default='United States', max_length=20)),
                ('region', models.CharField(default='Florida', max_length=20)),
                ('city', models.CharField(default='Florida', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cover_image', models.FileField(default='/media/posts/iceland.jpg', upload_to='posts')),
                ('status', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Categ')),
            ],
        ),
    ]
