# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categ',
            name='cover_image',
            field=models.FileField(default='/media/posts/iceland.jpg', upload_to='posts'),
        ),
    ]
