# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 20:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('ADV', 'Adventure Travel'), ('ART', 'Art & Culture'), ('BCK', 'Backpacking'), ('FAM', 'Family Holydays'), ('FOD', 'Food & Drink'), ('ROD', 'Road Trips'), ('BGT', 'On a budget'), ('WIL', 'Wildlife & Nature')], default='ADV', max_length=3)),
                ('description', models.TextField(default='Description')),
                ('country', models.CharField(default='United States', max_length=20)),
                ('region', models.CharField(default='Florida', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('photo', models.FileField(default='/media/posts/iceland.jpg', upload_to='posts')),
                ('status', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='author',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
