# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170208_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='categ',
            name='description',
            field=models.CharField(default='Get notified every time we publish a new tip, a new hack or a deal on Adventure Travel.', max_length=1000),
        ),
    ]
