# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_categ_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categ',
            name='description',
            field=models.TextField(default='Get notified every time we publish a new tip, a new hack or a deal on Adventure Travel.', max_length=1000),
        ),
    ]
